### ISSUE TITLE
Nullable types are not parsed correctly

### ISSUE THREAD

**Issue by xgouchet** [kotlinx/ast#13]
I'm parsing the following Kotlin code `kotlinx.ast` and the `KotlinGrammarAntlrKotlinParser`. But weirdly, I have some nullable types which are not marked as nullable.

```kotlin
package foo.bar
class Spam {
    fun doSomething(i: Int, s: String?, l : List<String>) {}
} 
```

Here's what I get when printing the AST nodes

```
PackageHeader(foo.bar)
importList
KlassDeclaration(object Spam)
PackageHeader(foo.bar)
importList
KlassDeclaration(class Spam)
  classBody
    KlassDeclaration(fun doSomething)
      KlassDeclaration(parameter i Int)
      KlassDeclaration(parameter s String)
      KlassDeclaration(parameter l List<String>)
```

I'm using version `c35b50fa44` from JitPack : 
```kotlin
implementation("com.github.kotlinx.ast:grammar-kotlin-parser-antlr-kotlin-jvm:c35b50fa44")
```

**Comment by xgouchet** [comment]
If I print the raw AST for the `s: String?` parameter, I get this, so the raw AST does know that the type is nullable : 

```
functionValueParameter
  parameter
    simpleIdentifier
      Identifier >>>s<<< (DEFAULT_TOKEN_CHANNEL)
    COLON >>>:<<< (DEFAULT_TOKEN_CHANNEL)
    Inside_WS >>> <<< (HIDDEN)
    type
      nullableType
        typeReference
          userType
            simpleUserType
              simpleIdentifier
                Identifier >>>String<<< (DEFAULT_TOKEN_CHANNEL)
        quest
          QUEST_NO_WS >>>?<<< (DEFAULT_TOKEN_CHANNEL)
```

**Comment by drieks** [comment]
Hi @xgouchet,

sorry for the late answer, I was very busy.. I will have a look, it should be easy to fix.

**Comment by drieks** [comment]
Hi @xgouchet,

I added your example as an unit test here https://github.com/kotlinx/ast/commit/bc5260ab4a22ddc421175cb06effa3587f3fb280 and fixed the missing nullable check here https://github.com/kotlinx/ast/commit/c6e164e3c0eb5747db58f8458a164cec96db0c74.

Please try the latest version and let me know if you have still issues.

**Comment by xgouchet** [comment]
Looks all good to me :) Thanks a lot
