### ISSUE TITLE
How to recursively print the structure of Ast

### ISSUE THREAD

**Issue by Symbolk** [kotlinx/ast#29]
Hi, thanks for the work!

I am fresh to Kotlin, and I want to convert a Kotlin file to AST.

Here is my Kotlin file:

```kt
package com.kickstarter.libs.utils

import android.content.Context
import android.net.Uri
import androidx.browser.customtabs.CustomTabsIntent
import androidx.core.content.ContextCompat
import com.kickstarter.R

object UrlUtils {

    private const val KEY_REF = "ref"

    fun appendPath(baseUrl: String, path: String): String {
        val uriBuilder = Uri.parse(baseUrl).buildUpon()
        uriBuilder.appendEncodedPath(path)

        return uriBuilder.build().toString()
    }

    fun appendQueryParameter(baseUrl: String, key: String, value: String): String {
        val uriBuilder = Uri.parse(baseUrl).buildUpon()
        uriBuilder.appendQueryParameter(key, value)

        return uriBuilder.build().toString()
    }

    fun appendRefTag(baseUrl: String, tag: String): String {
        return appendQueryParameter(baseUrl, KEY_REF, tag)
    }

    fun baseCustomTabsIntent(context: Context): CustomTabsIntent {
        val builder = CustomTabsIntent.Builder()

        builder.setShowTitle(true)
        builder.setToolbarColor(ContextCompat.getColor(context, R.color.primary))

        return builder.build()
    }

    fun refTag(url: String): String? {
        return Uri.parse(url).getQueryParameter(KEY_REF)
    }
}

```

Here is the test code:

```kt
package kotlinx.ast.example

import kotlinx.ast.common.AstSource
import kotlinx.ast.common.ast.Ast
import kotlinx.ast.common.print
import kotlinx.ast.grammar.kotlin.common.summary
import kotlinx.ast.grammar.kotlin.target.antlr.kotlin.KotlinGrammarAntlrKotlinParser

fun main() {
    val source = AstSource.File(
            "gen.kotlin/src/main/resources/2.kt.txt"
    )
    val kotlinFile = KotlinGrammarAntlrKotlinParser.parseKotlinFile(source)
    kotlinFile.summary(attachRawAst = false)
            .onSuccess { astList ->
                astList.forEach(Ast::print)
            }.onFailure { errors ->
                errors.forEach(::println)
            }
}
```

And here is the result, which only prints the top-level ones:

```
PackageHeader(com.kickstarter.libs.utils)
importList
  Import(android.content.Context)
  Import(android.net.Uri)
  Import(androidx.browser.customtabs.CustomTabsIntent)
  Import(androidx.core.content.ContextCompat)
  Import(com.kickstarter.R)
KlassDeclaration(object UrlUtils)

```
However, I found that the children for the top-level object AST is empty, then how to print the whole structure of the file?

**Comment by drieks** [comment]
Hi @Symbolk,

your example is parsed fine, I added a unit test here: https://github.com/kotlinx/ast/commit/a96e681f906f1ec1ab4db8a81ffbbcbbe529317f#diff-533d272ff7698c80d33e59cc079b9817e25a132371c50795c415d89da2189674

Maybe you are not using the latest version, there was a bug related to object parsing (https://github.com/kotlinx/ast/issues/28) fixed in january.

Please try `com.github.kotlinx.ast:grammar-kotlin-parser-antlr-java:5a03ad31d5` and let me know if this is also working for you.

**Comment by Symbolk** [comment]
> Hi @Symbolk,
> 
> your example is parsed fine, I added a unit test here: [a96e681#diff-533d272ff7698c80d33e59cc079b9817e25a132371c50795c415d89da2189674](https://github.com/kotlinx/ast/commit/a96e681f906f1ec1ab4db8a81ffbbcbbe529317f#diff-533d272ff7698c80d33e59cc079b9817e25a132371c50795c415d89da2189674)
> 
> Maybe you are not using the latest version, there was a bug related to object parsing (#28) fixed in january.
> 
> Please try `com.github.kotlinx.ast:grammar-kotlin-parser-antlr-java:5a03ad31d5` and let me know if this is also working for you.

Thanks, I was using `f9c929a8ab` as the JitPack tag suggests, but changing it with `5a03ad31d5` tends to work fine!

![image](https://user-images.githubusercontent.com/14107297/111863505-f4cb5c80-8996-11eb-8f47-26be08ba5960.png)

**Comment by drieks** [comment]
Hi @Symbolk,

thank you for the hint. I think I should switch it to version numbers.. I'm not sure why the JitPack tag is not pointing to the latest version...
