### ISSUE TITLE
KotlinGrammarAntlrKotlinParser very slow for files with json-strings

### ISSUE THREAD

**Issue by fab1an** [kotlinx/ast#50]
Creating a file like this:

````kotlin
package testpackage.

val LARGE_JSON = """
     <very large json with 77000 lines>
"""
````

Running
````kotlin
val source = AstSource.String("", stringSource)
val kotlinFile = KotlinGrammarAntlrKotlinParser.parseKotlinFile(source)
````

takes very long on a file like this. If I replace the JSON in the string with base64, it will be much faster.
Does the grammar somehow inspect the braces inside the templating?

**Comment by drieks** [comment]
Duplicate of #3
