### ISSUE TITLE
Installation of the Library

### ISSUE THREAD

**Issue by ckaanakyol** [kotlinx/ast#9]
Hello,

I am interested in code generation and worked on it couple of years. I want to implement some code generation app. I used to work with Clang, but decided to switch C++ to Kotlin.

I try to run the application on its own but failed to manage. Is there any way to run it on its own? 

Thanks,

**Comment by drieks** [comment]
Hello @ckaanakyol,

sorry for the late answer. This is no Code Generation Library, it contains currently just the parsing part. I'm using `kotlinx.ast` to parse Kotlin source files (I'm looking for Annotations) and `com.squareup:kotlinpoet` for code generation.
