### ISSUE TITLE
Add support for @JvmSuppressWildcards/ Annotations for types.

### ISSUE THREAD

**Issue by birajpatel** [kotlinx/ast#95]
Input: 
```
interface Something

class MyClass(
    list: List<@JvmSuppressWildcards Something>
)
```
Outputs: 
`found unsupported ast node 'KlassAnnotation(identifier=[KlassIdentifier(identifier=JvmSuppressWildcards ...`

**_Need:_** When using Kotlin & Java together, we need to often mark Generic types using `@JvmSuppressWildcards` to strip out `? extend Somthing` when kotlin code is compiled and used from Java. 
This is especially needed when using [Dagger with Kotlin](https://github.com/google/dagger/issues/900#issuecomment-359630229). 

Could you please add support for this? 
Thanks in advance :)

**Comment by birajpatel** [comment]
@drieks I can work on the potential fix & send you a PR, but just wanted to make sure you are still supporting the project before taking the efforts.

**Comment by drieks** [comment]
Hi, this would be great! I'm currently working on #89. Unfortunately I don't have much time for this at the moment, but feed free to ask any question!

I already created a unit test in the branch issue95.

**Comment by birajpatel** [comment]
@drieks Great I will propose a fix in coming days. I don't see the tests yet in branch `issue95`, may be you forgot to push the changes?
![Screenshot 2023-02-08 at 10 39 45](https://user-images.githubusercontent.com/2178182/217492582-a4df8be1-38eb-4c0d-bdae-e316aeec351e.png)

I am thinking the fix would be similar to [this fix](https://github.com/kotlinx/ast/commit/ee1cd9f8076e349b53941c49e8e62455eca3aeb3). 
Basically I plan to add `List<KlassAnnotations>` in `KlassIdentifier`, similar to your fix for `modifiers` let me know if that sounds ok?

Also I couldn't import the project, I keep getting : 
```
Could not GET 'https://mvnrepository.com/artifact/com.github.gundy/semver4j/com/github/drieks/antlr-kotlin/antlr-kotlin-gradle-plugin/ce9944fa0c/antlr-kotlin-gradle-plugin-ce9944fa0c.pom'. Received status code 403 from server: Forbidden
```

**Comment by drieks** [comment]
Hi @birajpatel,
I pushed master to the feature branch.. now the correct commit should be visible :)
Yes, this download problem is the reason for #89, I will try to publish both antlr-kotlin ant kotlinx.ast to maven central.
you can fix this by cloning antlr-kotlin locally, then publish to local maven:
```
./gradlew clean publishToMavenLocal -x test
```
after this, you can change the local reference in build.gradle.kts in kotlinx.ast to you local dependency

**Comment by drieks** [comment]
Hi @birajpatel, thank you, I merged your changes!
