### ISSUE TITLE
How do I rely on this project on Maven? 

### ISSUE THREAD

**Issue by heyuxiang1996** [kotlinx/ast#99]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>untitled</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>

    <dependencies>
        
        <dependency>
            <groupId>com.github.kotlinx.ast</groupId>
            <artifactId>grammar-kotlin-parser-common-jvm</artifactId>
            <version>57524bbb21</version>
        </dependency>
    </dependencies>

</project>

**Comment by heyuxiang1996** [comment]
This is my pom file code, and the IDE prompts that it cannot be loaded (refresh also cannot resolve). Looking forward to your reply, thank you very much!

**Comment by heyuxiang1996** [comment]
Does kotlinx.ast only support kotlin projects? Can Java projects built using Maven use it?

**Comment by LiuShiYi1027** [comment]
> 

I have encountered the same problem.

here is my `pom.xml`, but it can not import the class in the java file.
<img width="772" alt="image" src="https://user-images.githubusercontent.com/28551556/229430925-f0062b56-e765-494b-8d3b-6b55d50f51e9.png">

the jar file has been imported in Libraries

**Comment by akarahdev** [comment]
Hi! I had a similar issue.
For anyone who is here sometime in the future, where it says the repository is valid but it won't work in your code, try this:

1. Right click on your project name - mine is CKotlin.
![image](https://github.com/kotlinx/ast/assets/118059229/55717dd3-0945-48ab-8861-be2b3c3d3424)
2. It should bring up this menu
![image](https://github.com/kotlinx/ast/assets/118059229/0bf4d6be-3171-4e25-905c-b1bde2009c71)
3. Go into `Maven` and select `Reload Project`.
![image](https://github.com/kotlinx/ast/assets/118059229/09064c4e-854e-4b92-ab19-e9d7ac20eed3)

This effectively just tells Maven to re-install every import from the looks of it. I don't know if this will work for others, but try it anyways I guess.
